# Generated by Django 3.1.6 on 2021-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0003_auto_20210212_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
