# Generated by Django 3.1.6 on 2021-02-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0005_auto_20210213_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='DOB',
        ),
    ]
