# Generated by Django 3.1.6 on 2021-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0006_remove_userlogin_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='DOB',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
