# Generated by Django 3.1.6 on 2021-02-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0007_userlogin_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='f_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='l_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
