# Generated by Django 3.1.6 on 2021-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0008_auto_20210213_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='f_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
