# Generated by Django 3.1.6 on 2021-02-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0009_auto_20210213_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email_id',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
