# Generated by Django 3.1.6 on 2021-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_with_apiviews', '0011_auto_20210215_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email_id',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
    ]
