# Generated by Django 3.1.6 on 2021-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('email_id', models.EmailField(max_length=70, null=True, unique=True)),
                ('location', models.TextField()),
            ],
        ),
    ]
