# Generated by Django 3.1.6 on 2021-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WWE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(default=None, max_length=100)),
                ('p_lock', models.CharField(default=None, max_length=100)),
                ('p_chest', models.IntegerField(blank=True, null=True)),
                ('p_height', models.IntegerField(blank=True, null=True)),
                ('p_color', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
