# Generated by Django 3.1.6 on 2021-02-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_without_serializers', '0004_auto_20210216_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwe',
            name='p_lock',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
